// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cjmkbixlyiukpdvkxyja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqbWtiaXhseWl1a3Bkdmt4eWphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDIyMjUsImV4cCI6MjA3NzU3ODIyNX0.3vyckq55hbV93YV2KJfUW-b6C1UIPfCtKzIzlqA_xh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});